[workspace]
members = [
    "bip39",
    "chain-path-derivation",
    "hdkeygen",
    "wallet",
    "shield-protocol",
    "bindings/wallet-c",
    "bindings/wallet-jni",
    "bindings/wallet-js",
]

exclude = [
    "chain-deps",
]

[profile.release]
lto = "yes"