name: Testing Workflow

# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      = master
      - gh_actions_test

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Step 3: Check the code with Android linter
      - name: Run Android Linte
        run: . ./wallet-android/gradlew lintStagingDebug

      # Step 4: Run your unit tests
      - name: Run Unit Tests
        run:  ./wallet-android/gradlew testStagingDebugUnitTest