name: Android tests

# Step 1: Choose the branch or branches you want to run this workflow
on: [push, pull_request]

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Step 3: Check the code with Android linter
      - name: Run Android Lint
        working-directory: ./wallet-android
        run: ./gradlew lint

      # Step 4: Check the code with Android linter
      - name: Run Android build
        working-directory: ./wallet-android
        run: ./gradlew build

      # Step 5: Run your unit tests
      - name: Run Unit Tests
        working-directory: ./wallet-android
        run:  ./gradlew test